site_name: Documentação - Curso GitHub Descomplicado
site_url: 
theme:
    name: material
    markdown_extensions:
        - abbr
        - admonition
        - pymdownx.details
        - pymdownx.superfences:
            custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
        - attr_list
        - md_in_html
        - attr_list
        - def_list
        - pymdownx.critic
        - pymdownx.caret
        - pymdownx.keys
        - pymdownx.mark
        - pymdownx.tilde
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed:
            alternate_style: true
        - toc:
            permalink: true
        - codehilite
        - pymdownx.highlight
        - pymdownx.inlinehilite
        - pymdownx.smartsymbols
        - toc:
            permalink: "#"
        - pymdownx.arithmatex:
            generic: true
        
    features:
        - tabs
        - instant
        - navigation.instant
        - navigation.tabs
        - search.highlight
        - content.code.copy
        - navigation.footer
        - navigation.top
        - content.tabs.link
    language: en
    palette:
        # Light Mode
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          accent: orange
        # Dark Mode
        - scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
          accent: lime

nav:
    - Introdução:
        - Curso GitHub Descomplicado: index.md
    - Introdução ao Git e GitHub: 
        - Apresentação da Aula: aula01/apresentacao.md
        - Conteúdo: aula01/conteudo.md
    - Trabalhando com Repositórios: 
        - Apresentação da Aula: aula02/apresentacao.md
        - Conteúdo: aula02/conteudo.md
    - Colaboração e Fluxo de Trabalho: 
        - Apresentação da Aula: aula03/apresentacao.md
        - Conteúdo: aula03/conteudo.md
    - GitHub Pages: 
        - Apresentação da Aula: aula03/apresentacao.md
        - Conteúdo: aula03/conteudo.md
    - Trabalho Final do Curso: trabalho/informacoes.md

markdown_extensions:
    - md_in_html
    - admonition
    - codehilite
    - def_list
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - toc:
        permalink: "#"

# Configuration
repo_url: 
repo_name: 